In [58]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
from datetime import datetime

In [62]:
#Import data
df = pd.read_csv(os.path.join("C:\\Users\\kam52\\OneDrive\\Desktop\\DA1\\Project\\query_EQ.csv"), parse_dates=['time'])
df

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2022-06-15 23:52:07.457000+00:00,26.655600,54.263800,10.00,4.10,mb,NaN,117.0,2.44100,0.83,...,2022-06-16T00:04:29.040Z,"26 km ENE of K?sh, Iran",earthquake,8.10,2.00,0.144,13.0,reviewed,us,us
1,2022-06-15 22:23:44.855000+00:00,23.850500,143.262500,10.00,5.00,mb,NaN,85.0,12.67300,0.91,...,2022-06-15T22:41:27.040Z,"Volcano Islands, Japan region",earthquake,10.60,1.80,0.044,162.0,reviewed,us,us
2,2022-06-15 22:17:29.586000+00:00,-22.880300,-179.068200,531.95,4.50,mb,NaN,132.0,5.77900,0.96,...,2022-06-15T22:35:39.040Z,south of the Fiji Islands,earthquake,12.10,15.80,0.140,15.0,reviewed,us,us
3,2022-06-15 21:54:33.450000+00:00,18.604600,-65.058100,31.00,3.53,md,14.0,252.0,0.26890,0.18,...,2022-06-15T22:29:04.040Z,"32 km NNW of Charlotte Amalie, U.S. Virgin Isl...",earthquake,0.95,1.33,0.050,12.0,reviewed,pr,pr
4,2022-06-15 20:58:13.747000+00:00,26.687200,54.270400,10.00,4.20,mb,NaN,116.0,2.45900,0.81,...,2022-06-16T20:43:39.040Z,"28 km ENE of K?sh, Iran",earthquake,5.50,1.90,0.136,15.0,reviewed,us,us
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11534,2022-01-01 02:17:56.815000+00:00,38.725100,73.482700,105.79,4.20,mb,NaN,95.0,1.50900,1.01,...,2022-03-12T22:18:59.040Z,"74 km NW of Murghob, Tajikistan",earthquake,6.40,8.30,0.153,13.0,reviewed,us,us
11535,2022-01-01 01:38:57.636000+00:00,52.922000,-163.660500,10.00,3.10,ml,NaN,257.0,1.69500,0.47,...,2022-03-12T22:19:25.040Z,"194 km SE of Akutan, Alaska",earthquake,3.60,1.90,0.105,12.0,reviewed,us,us
11536,2022-01-01 00:27:51.990000+00:00,40.477167,-124.322333,19.08,2.88,md,27.0,122.0,0.01167,0.10,...,2022-03-12T22:18:59.040Z,"12km SSW of Ferndale, CA",earthquake,0.34,0.19,0.221,43.0,reviewed,nc,nc
11537,2022-01-01 00:10:28.735000+00:00,-8.763300,124.351300,104.90,4.10,mb,NaN,68.0,0.98900,0.69,...,2022-03-12T22:18:59.040Z,"48 km N of Pante Makasar, Timor Leste",earthquake,6.70,8.40,0.197,7.0,reviewed,us,us
11538,2022-01-01 00:02:24.512000+00:00,-17.026900,-174.214200,60.87,4.60,mb,NaN,85.0,3.88600,0.17,...,2022-03-12T22:19:16.040Z,"126 km SSW of Hihifo, Tonga",earthquake,12.60,6.40,0.273,4.0,reviewed,us,us

In [63]:
#To check data types
df.dtypes

time               datetime64[ns, UTC]
latitude                       float64
longitude                      float64
depth                          float64
mag                            float64
magType                         object
nst                            float64
gap                            float64
dmin                           float64
rms                            float64
net                             object
id                              object
updated                         object
place                           object
type                            object
horizontalError                float64
depthError                     float64
magError                       float64
magNst                         float64
status                          object
locationSource                  object
magSource                       object
dtype: object

In [64]:
#To check data file type
type(df)

pandas.core.frame.DataFrame

In [65]:
#To copy datafile to work with
df2 = df.copy()
print(df2)

                                  time   latitude   longitude   depth   mag  \
0     2022-06-15 23:52:07.457000+00:00  26.655600   54.263800   10.00  4.10
1     2022-06-15 22:23:44.855000+00:00  23.850500  143.262500   10.00  5.00
2     2022-06-15 22:17:29.586000+00:00 -22.880300 -179.068200  531.95  4.50
3     2022-06-15 21:54:33.450000+00:00  18.604600  -65.058100   31.00  3.53
4     2022-06-15 20:58:13.747000+00:00  26.687200   54.270400   10.00  4.20
...                                ...        ...         ...     ...   ...
11534 2022-01-01 02:17:56.815000+00:00  38.725100   73.482700  105.79  4.20
11535 2022-01-01 01:38:57.636000+00:00  52.922000 -163.660500   10.00  3.10
11536 2022-01-01 00:27:51.990000+00:00  40.477167 -124.322333   19.08  2.88
11537 2022-01-01 00:10:28.735000+00:00  -8.763300  124.351300  104.90  4.10
11538 2022-01-01 00:02:24.512000+00:00 -17.026900 -174.214200   60.87  4.60

      magType   nst    gap      dmin   rms  ...                   updated  \
0          mb   NaN  117.0   2.44100  0.83  ...  2022-06-16T00:04:29.040Z
1          mb   NaN   85.0  12.67300  0.91  ...  2022-06-15T22:41:27.040Z
2          mb   NaN  132.0   5.77900  0.96  ...  2022-06-15T22:35:39.040Z
3          md  14.0  252.0   0.26890  0.18  ...  2022-06-15T22:29:04.040Z
4          mb   NaN  116.0   2.45900  0.81  ...  2022-06-16T20:43:39.040Z
...       ...   ...    ...       ...   ...  ...                       ...
11534      mb   NaN   95.0   1.50900  1.01  ...  2022-03-12T22:18:59.040Z
11535      ml   NaN  257.0   1.69500  0.47  ...  2022-03-12T22:19:25.040Z
11536      md  27.0  122.0   0.01167  0.10  ...  2022-03-12T22:18:59.040Z
11537      mb   NaN   68.0   0.98900  0.69  ...  2022-03-12T22:18:59.040Z
11538      mb   NaN   85.0   3.88600  0.17  ...  2022-03-12T22:19:16.040Z

                                                   place        type  \
0                                26 km ENE of K?sh, Iran  earthquake
1                          Volcano Islands, Japan region  earthquake
2                              south of the Fiji Islands  earthquake
3      32 km NNW of Charlotte Amalie, U.S. Virgin Isl...  earthquake
4                                28 km ENE of K?sh, Iran  earthquake
...                                                  ...         ...
11534                    74 km NW of Murghob, Tajikistan  earthquake
11535                        194 km SE of Akutan, Alaska  earthquake
11536                           12km SSW of Ferndale, CA  earthquake
11537              48 km N of Pante Makasar, Timor Leste  earthquake
11538                        126 km SSW of Hihifo, Tonga  earthquake

      horizontalError depthError  magError  magNst    status  locationSource  \
0                8.10       2.00     0.144    13.0  reviewed              us
1               10.60       1.80     0.044   162.0  reviewed              us
2               12.10      15.80     0.140    15.0  reviewed              us
3                0.95       1.33     0.050    12.0  reviewed              pr
4                5.50       1.90     0.136    15.0  reviewed              us
...               ...        ...       ...     ...       ...             ...
11534            6.40       8.30     0.153    13.0  reviewed              us
11535            3.60       1.90     0.105    12.0  reviewed              us
11536            0.34       0.19     0.221    43.0  reviewed              nc
11537            6.70       8.40     0.197     7.0  reviewed              us
11538           12.60       6.40     0.273     4.0  reviewed              us

      magSource
0            us
1            us
2            us
3            pr
4            us
...         ...
11534        us
11535        us
11536        nc
11537        us
11538        us

[11539 rows x 22 columns]

In [66]:
#To check copied file
df2.dtypes

time               datetime64[ns, UTC]
latitude                       float64
longitude                      float64
depth                          float64
mag                            float64
magType                         object
nst                            float64
gap                            float64
dmin                           float64
rms                            float64
net                             object
id                              object
updated                         object
place                           object
type                            object
horizontalError                float64
depthError                     float64
magError                       float64
magNst                         float64
status                          object
locationSource                  object
magSource                       object
dtype: object

In [67]:
#To check copied file
type(df2)

pandas.core.frame.DataFrame

In [68]:
#To seperate date and time
df2['date'] = [d.date() for d in df2['time']]
df2['time'] = [d.time() for d in df2['time']]
df2

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,date
0,23:52:07.457000,26.655600,54.263800,10.00,4.10,mb,NaN,117.0,2.44100,0.83,...,"26 km ENE of K?sh, Iran",earthquake,8.10,2.00,0.144,13.0,reviewed,us,us,2022-06-15
1,22:23:44.855000,23.850500,143.262500,10.00,5.00,mb,NaN,85.0,12.67300,0.91,...,"Volcano Islands, Japan region",earthquake,10.60,1.80,0.044,162.0,reviewed,us,us,2022-06-15
2,22:17:29.586000,-22.880300,-179.068200,531.95,4.50,mb,NaN,132.0,5.77900,0.96,...,south of the Fiji Islands,earthquake,12.10,15.80,0.140,15.0,reviewed,us,us,2022-06-15
3,21:54:33.450000,18.604600,-65.058100,31.00,3.53,md,14.0,252.0,0.26890,0.18,...,"32 km NNW of Charlotte Amalie, U.S. Virgin Isl...",earthquake,0.95,1.33,0.050,12.0,reviewed,pr,pr,2022-06-15
4,20:58:13.747000,26.687200,54.270400,10.00,4.20,mb,NaN,116.0,2.45900,0.81,...,"28 km ENE of K?sh, Iran",earthquake,5.50,1.90,0.136,15.0,reviewed,us,us,2022-06-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11534,02:17:56.815000,38.725100,73.482700,105.79,4.20,mb,NaN,95.0,1.50900,1.01,...,"74 km NW of Murghob, Tajikistan",earthquake,6.40,8.30,0.153,13.0,reviewed,us,us,2022-01-01
11535,01:38:57.636000,52.922000,-163.660500,10.00,3.10,ml,NaN,257.0,1.69500,0.47,...,"194 km SE of Akutan, Alaska",earthquake,3.60,1.90,0.105,12.0,reviewed,us,us,2022-01-01
11536,00:27:51.990000,40.477167,-124.322333,19.08,2.88,md,27.0,122.0,0.01167,0.10,...,"12km SSW of Ferndale, CA",earthquake,0.34,0.19,0.221,43.0,reviewed,nc,nc,2022-01-01
11537,00:10:28.735000,-8.763300,124.351300,104.90,4.10,mb,NaN,68.0,0.98900,0.69,...,"48 km N of Pante Makasar, Timor Leste",earthquake,6.70,8.40,0.197,7.0,reviewed,us,us,2022-01-01
11538,00:02:24.512000,-17.026900,-174.214200,60.87,4.60,mb,NaN,85.0,3.88600,0.17,...,"126 km SSW of Hihifo, Tonga",earthquake,12.60,6.40,0.273,4.0,reviewed,us,us,2022-01-01

In [69]:

print(df2)

                  time   latitude   longitude   depth   mag magType   nst  \
0      23:52:07.457000  26.655600   54.263800   10.00  4.10      mb   NaN
1      22:23:44.855000  23.850500  143.262500   10.00  5.00      mb   NaN
2      22:17:29.586000 -22.880300 -179.068200  531.95  4.50      mb   NaN
3      21:54:33.450000  18.604600  -65.058100   31.00  3.53      md  14.0
4      20:58:13.747000  26.687200   54.270400   10.00  4.20      mb   NaN
...                ...        ...         ...     ...   ...     ...   ...
11534  02:17:56.815000  38.725100   73.482700  105.79  4.20      mb   NaN
11535  01:38:57.636000  52.922000 -163.660500   10.00  3.10      ml   NaN
11536  00:27:51.990000  40.477167 -124.322333   19.08  2.88      md  27.0
11537  00:10:28.735000  -8.763300  124.351300  104.90  4.10      mb   NaN
11538  00:02:24.512000 -17.026900 -174.214200   60.87  4.60      mb   NaN

         gap      dmin   rms  ...  \
0      117.0   2.44100  0.83  ...
1       85.0  12.67300  0.91  ...
2      132.0   5.77900  0.96  ...
3      252.0   0.26890  0.18  ...
4      116.0   2.45900  0.81  ...
...      ...       ...   ...  ...
11534   95.0   1.50900  1.01  ...
11535  257.0   1.69500  0.47  ...
11536  122.0   0.01167  0.10  ...
11537   68.0   0.98900  0.69  ...
11538   85.0   3.88600  0.17  ...

                                                   place        type  \
0                                26 km ENE of K?sh, Iran  earthquake
1                          Volcano Islands, Japan region  earthquake
2                              south of the Fiji Islands  earthquake
3      32 km NNW of Charlotte Amalie, U.S. Virgin Isl...  earthquake
4                                28 km ENE of K?sh, Iran  earthquake
...                                                  ...         ...
11534                    74 km NW of Murghob, Tajikistan  earthquake
11535                        194 km SE of Akutan, Alaska  earthquake
11536                           12km SSW of Ferndale, CA  earthquake
11537              48 km N of Pante Makasar, Timor Leste  earthquake
11538                        126 km SSW of Hihifo, Tonga  earthquake

      horizontalError depthError magError  magNst    status  locationSource  \
0                8.10       2.00    0.144    13.0  reviewed              us
1               10.60       1.80    0.044   162.0  reviewed              us
2               12.10      15.80    0.140    15.0  reviewed              us
3                0.95       1.33    0.050    12.0  reviewed              pr
4                5.50       1.90    0.136    15.0  reviewed              us
...               ...        ...      ...     ...       ...             ...
11534            6.40       8.30    0.153    13.0  reviewed              us
11535            3.60       1.90    0.105    12.0  reviewed              us
11536            0.34       0.19    0.221    43.0  reviewed              nc
11537            6.70       8.40    0.197     7.0  reviewed              us
11538           12.60       6.40    0.273     4.0  reviewed              us

       magSource        date
0             us  2022-06-15
1             us  2022-06-15
2             us  2022-06-15
3             pr  2022-06-15
4             us  2022-06-15
...          ...         ...
11534         us  2022-01-01
11535         us  2022-01-01
11536         nc  2022-01-01
11537         us  2022-01-01
11538         us  2022-01-01

[11539 rows x 23 columns]

In [7]:
#Smaller data set to be discarded if not used
may = pd.read_csv(os.path.join("C:\\Users\\kam52\\OneDrive\\Desktop\\DA1\\Project\\may_EQ.csv"))
may

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2022-06-18T01:04:49.490Z,19.164667,-155.494995,33.169998,2.98,ml,45.0,108.0,NaN,0.12,...,2022-06-18T01:26:00.726Z,"4 km SSW of P?hala, Hawaii",earthquake,0.46,0.63,3.430000,29.0,automatic,hv,hv
1,2022-06-18T00:03:04.971Z,26.658700,54.242400,10.000000,4.10,mb,NaN,79.0,2.45700,0.73,...,2022-06-18T00:19:37.040Z,"24 km ENE of K?sh, Iran",earthquake,8.20,1.90,0.094000,31.0,reviewed,us,us
2,2022-06-17T23:47:52.330Z,35.109833,-119.003998,12.240000,3.11,ml,83.0,30.0,0.08304,0.32,...,2022-06-18T00:50:06.463Z,"19km SSW of Lamont, CA",earthquake,0.26,1.04,0.207000,23.0,automatic,ci,ci
3,2022-06-17T23:28:47.360Z,17.938000,-66.849000,13.470000,2.74,md,8.0,215.0,NaN,0.14,...,2022-06-18T01:12:57.920Z,"6 km SE of Maria Antonia, Puerto Rico",earthquake,0.85,0.43,0.116466,5.0,reviewed,pr,pr
4,2022-06-17T23:04:22.810Z,19.197666,-155.436172,32.650002,2.80,ml,47.0,138.0,NaN,0.13,...,2022-06-17T23:17:01.040Z,"4 km E of P?hala, Hawaii",earthquake,0.51,0.62,3.710000,28.0,automatic,hv,hv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,2022-06-11T03:01:06.019Z,54.939700,160.414300,129.310000,4.30,mb,NaN,115.0,2.18400,1.00,...,2022-06-11T03:33:03.040Z,"88 km SSE of Atlasovo, Russia",earthquake,11.50,5.20,0.102000,29.0,reviewed,us,us
304,2022-06-11T02:05:54.252Z,36.015300,31.376100,62.120000,4.30,mb,NaN,46.0,1.39200,0.89,...,2022-06-12T12:33:32.259Z,"76 km SSW of Okurcalar, Turkey",earthquake,6.20,8.20,0.091000,36.0,reviewed,us,us
305,2022-06-11T02:04:58.500Z,18.057167,-66.864167,15.840000,2.56,md,6.0,121.0,NaN,0.12,...,2022-06-11T04:05:03.527Z,"2 km NNW of Yauco, Puerto Rico",earthquake,0.49,1.18,0.005805,3.0,reviewed,pr,pr
306,2022-06-11T01:49:43.330Z,17.985333,-68.161167,9.800000,3.34,md,9.0,215.0,NaN,0.48,...,2022-06-11T02:15:22.460Z,"64 km SE of Boca de Yuma, Dominican Republic",earthquake,3.32,31.61,0.095646,8.0,reviewed,pr,pr
307,2022-06-11T00:26:40.631Z,0.285800,122.203300,173.690000,4.30,mb,NaN,74.0,1.43600,0.59,...,2022-06-17T04:48:35.040Z,"99 km WSW of Gorontalo, Indonesia",earthquake,10.60,9.60,0.133000,16.0,reviewed,us,us